version: '3'

volumes:
  keycloak_postgres_data:
    driver: local

services:
  postgres:
    container_name: keycloak-postgres
    image: postgres
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8100:8100
    depends_on:
      - postgres
    command:
      - start-dev
      - --http-port=8100
    restart: always